# Este arquivo contém mapeamentos do tipo:
# [valor original] -> [valor corrigido]


SIGLAS_UF = {
   "Acre"                 : "AC",
   "Alagoas"              : "AL",
   "Amapá"                : "AP",
   "Amazonas"             : "AM",
   "Bahia"                : "BA",
   "Ceará"                : "CE",
   "Distrito Federal"     : "DF",
   "Espírito Santo"       : "ES",
   "Goiás"                : "GO",
   "Maranhão"             : "MA",
   "Mato Grosso"          : "MT",
   "Mato Grosso do Sul"   : "MS",
   "Minas Gerais"         : "MG",
   "Pará"                 : "PA",
   "Paraíba"              : "PB",
   "Paraná"               : "PR",
   "Pernambuco"           : "PE",
   "Piauí"                : "PI",
   "Rio de Janeiro"       : "RJ",
   "Rio Grande do Norte"  : "RN",
   "Rio Grande do Sul"    : "RS",
   "Rondônia"             : "RO",
   "Roraima"              : "RR",
   "Santa Catarina"       : "SC",
   "São Paulo"            : "SP",
   "Sergipe"              : "SE",
   "Tocantins"            : "TO"
}


CORRECOES_MUNICIPIOS = {
   ("BA", "LAGEDO DO TABOCAL")              : "LAJEDO DO TABOCAL",
   ("BA", "SANTA TERESINHA")                : "SANTA TEREZINHA",
   ("GO", "BOM JESUS")                      : "BOM JESUS DE GOIAS",
   ("MG", "AMPARO DA SERRA")                : "AMPARO DO SERRA",
   ("MG", "BARAO D0 MONTE ALTO")            : "BARAO DO MONTE ALTO",
   ("MG", "BRASOPOLIS")                     : "BRAZOPOLIS",
   ("MG", "GOUVEA")                         : "GOUVEIA",
   ("MG", "QUELUZITA")                      : "QUELUZITO",
   ("MT", "POXOREO")                        : "POXOREU",
   ("MT", "SANTO ANTONIO DO LEVERGER")      : "SANTO ANTONIO DE LEVERGER",
   ("MT", "VILA BELA DA SANTISSIMA TRINDA") : "VILA BELA DA SANTISSIMA TRINDADE",
   ("PA", "ELDORADO DOS CARAJAS")           : "ELDORADO DO CARAJAS",
   ("PA", "SANTA ISABEL DO PARA")           : "SANTA IZABEL DO PARA",
   ("PB", "CAMPO DE SANTANA")               : "TACIMA",
   ("PB", "SANTAREM")                       : "JOCA CLAUDINO",
   ("PB", "SAO DOMINGOS DE POMBAL")         : "SAO DOMINGOS",
   ("PE", "BELEM DE SAO FRANCISCO")         : "BELEM DO SAO FRANCISCO",
   ("PE", "IGUARACI")                       : "IGUARACY",
   ("PE", "LAGOA DO ITAENGA")               : "LAGOA DE ITAENGA",
   ("PI", "SAO FRANCISCO DE ASSIS DO PIAU") : "SAO FRANCISCO DE ASSIS DO PIAUI",
   ("PR", "BELA VISTA DO CAROBA")           : "BELA VISTA DA CAROBA",
   ("PR", "MUNHOZ DE MELLO")                : "MUNHOZ DE MELO",
   ("PR", "PINHAL DO SAO BENTO")            : "PINHAL DE SAO BENTO",
   ("PR", "SANTA CRUZ DO MONTE CASTELO")    : "SANTA CRUZ DE MONTE CASTELO",
   ("RJ", "ARMACAO DE BUZIOS")              : "ARMACAO DOS BUZIOS",
   ("RJ", "PARATI")                         : "PARATY",
   ("RJ", "TRAJANO DE MORAIS")              : "TRAJANO DE MORAES",
   ("RN", "ASSU")                           : "ACU",
   ("RN", "BOA SAUDE")                      : "JANUARIO CICCO",
   ("RN", "LAGOA DANTA")                    : "LAGOA D ANTA",
   ("RO", "NOVA DO MAMORE")                 : "NOVA MAMORE",
   ("RS", "SANTANA DO LIVRAMENTO")          : "SANT ANA DO LIVRAMENTO",
   ("SC", "BALNEARIO DE PICARRAS")          : "BALNEARIO PICARRAS",
   ("SC", "LAGEADO GRANDE")                 : "LAJEADO GRANDE",
   ("SC", "PRESIDENTE CASTELO BRANCO")      : "PRESIDENTE CASTELLO BRANCO",
   ("SC", "SAO LOURENCO D OESTE")           : "SAO LOURENCO DO OESTE",
   ("SC", "SAO MIGUEL D OESTE")             : "SAO MIGUEL DO OESTE",
   ("SE", "AMPARO DE SAO FRANCISCO")        : "AMPARO DO SAO FRANCISCO",
   ("SP", "EMBU")                           : "EMBU DAS ARTES",
   ("TO", "COUTO DE MAGALHAES")             : "COUTO MAGALHAES",
   ("TO", "FORTALEZA DO TABOCAO")           : "TABOCAO",
   ("TO", "SAO VALERIO DA NATIVIDADE")      : "SAO VALERIO",
}
